#! /bin/sh

env \
    __GL_GSYNC_ALLOWED=0 \
    __GL_VRR_ALLOWED=0 \
    __GLX_VENDOR_LIBRARY_NAME=nvidia \
    GDK_BACKEND=wayland \
    GBM_BACKEND=nvidia-drm \
    MOZ_ENABLE_WAYLAND=1 \
    QT_AUTO_SCREEN_SCALE_FACTOR=1 \
    QT_QPA_PLATFORM=wayland \
    QT_WAYLAND_DISABLE_WINDOWDECORATION=1 \
    WLR_DRM_NO_ATOMIC=1 \
    WLR_NO_HARDWARE_CURSORS=1 \
    WLR_RENDERER=vulkan \
    XDG_CURRENT_DESKTOP=wlroots \
    qtile start -n -b wayland -c ~/.config/qtile/config.py
